version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: m4d-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PRODUCT_ID=${STRIPE_PRODUCT_ID}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
    env_file:
      - .env.production
